# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IRTpp <- function(data, model, dim, initVal, epsilonConv, maxIter, verbose) {
    .Call('IRTpp_IRTpp', PACKAGE = 'IRTpp', data, model, dim, initVal, epsilonConv, maxIter, verbose)
}

rcpp_hello_world <- function() {
    .Call('IRTpp_rcpp_hello_world', PACKAGE = 'IRTpp')
}

